import DashboardHeader from './(dashboardHeader)/DashboardHeader'
import DashboardMenuDesktop from './(dashboardMenu)/DashboardMenuDesktop'
import DashboardMenuMobile from './(dashboardMenu)/DashboardMenuMobile'

export const revalidate = 30

export const metadata = {
  title: {
    default: `Dashboard`,
    template: `%s - Sports Agent Pro`,
  },
  // description: 'Generated by create next app',
}

export default async function DashboardLayout({ children }) {
  return (
    <div className={`block md:flex h-screen`}>
      <div className={'hidden lg:block'}>
        <DashboardMenuDesktop />
      </div>
      <div className={'block lg:hidden'}>
        <DashboardMenuMobile />
      </div>
      <div className={'flex flex-col w-full lg:gap-5 lg:bg-[#f6fafd]'}>
        <DashboardHeader />
        <div
          className={
            'lg:px-5 max-h-screen border-t-[1px] border-[#F7F7F7] lg:border-t-none overflow-y-auto box-border relative'
          }
        >
          <div className={'flex flex-col lg:rounded-md'}>{children}</div>
        </div>
      </div>
    </div>
  )
}
