import React from 'react'

export const metadata = {
  title: 'Sports Agent Pro',
  // description: 'Generated by create next app',
}

const Homepage = () => {
  return (
    <>
      {/* <MainNavigation /> */}
      {/* <div className={`${openSans.className}`}> */}
      <p className={''}>Homepage</p>
      {/* </div> */}
      {/* <Footer /> */}
    </>
  )
}

export default Homepage
