import LoginPage from './(auth)/login/page'

export const metadata = {
  title: 'Sports Agent Pro',
  // description: 'Generated by create next app',
}

const Homepage = async () => {
  // const isLoggedIn = await getCurrentUser()
  // redirect(isLoggedIn ? '/dashboard' : '/login')
  return (
    <>
      <LoginPage />
    </>
  )
}

export default Homepage
