import React from 'react'
import LogoutButton from '../_(dashboardHeader)/LogoutButton'
// import ClientDashboard from './ClientDashboard'

export const metadata = {
  title: {
    default: `Dashboard`,
    template: `%s - Love Transfusion`,
  },
  // description: 'Generated by create next app',
}

const DashboardPage = async () => {
  return (
    <>
      <p className={''}>Dashboard</p>
      <LogoutButton />
      {/* <ClientDashboard /> */}
    </>
  )
}

export default DashboardPage
