import React from 'react'
import ClientDashboard from './ClientDashboard'
import ContentContainerDashboard from '@/app/components/ThisWebsiteOnly/Dashboard/ContentContainerDashboard'

export const metadata = {
  title: {
    default: `Dashboard`,
    template: `%s - Love Transfusion`,
  },
  // description: 'Generated by create next app',
}

const DashboardPage = async () => {
  return (
    <ContentContainerDashboard>
      <ClientDashboard />
    </ContentContainerDashboard>
  )
}

export default DashboardPage
