export const listBrandWhichBestDescribesYou = [
  { name: 'Property', value: 'property' },
  { name: 'Advertiser', value: 'advertiser' },
  { name: 'Publisher', value: 'publisher' },
  { name: 'Businessperson', value: 'businessperson' },
  { name: 'College affiliate', value: 'college_affiliate' },
  { name: 'Other', value: 'other' },
]

export const listAthleticAccolades = [
  { name: 'Olympic Gold Medal', value: 'olympic_gold_medal' },
  { name: 'World Championship Title', value: 'world_championship_title' },
  { name: 'Super Bowl MVP', value: 'super_bowl_mvp' },
  { name: 'MVP (Most Valuable Player)', value: 'mvp_most_valuable_player' },
  { name: 'Heisman Trophy', value: 'heisman_trophy' },
  { name: 'NBA Finals MVP', value: 'nba_finals_mvp' },
  {
    name: 'Triple Crown Winner (Horse Racing)',
    value: 'triple_crown_winner_horse_racing',
  },
  { name: 'Golden Boot Award (Soccer)', value: 'golden_boot_award_soccer' },
  { name: 'Grand Slam (Tennis)', value: 'grand_slam_tennis' },
  {
    name: 'Green Jacket (The Masters Golf Tournament)',
    value: 'green_jacket_masters_golf_tournament',
  },
  { name: 'Stanley Cup Champion', value: 'stanley_cup_champion' },
  { name: 'World Series Champion', value: 'world_series_champion' },
  {
    name: 'Tour de France Yellow Jersey',
    value: 'tour_de_france_yellow_jersey',
  },
  {
    name: 'UEFA Champions League Winner',
    value: 'uefa_champions_league_winner',
  },
  { name: 'All-Star Selection', value: 'all_star_selection' },
  { name: 'Indy 500 Winner', value: 'indy_500_winner' },
  { name: 'Gold Gloves (Boxing)', value: 'gold_gloves_boxing' },
  { name: 'PGA Tour Player of the Year', value: 'pga_tour_player_of_the_year' },
  {
    name: 'Silver Slugger Award (Baseball)',
    value: 'silver_slugger_award_baseball',
  },
  {
    name: 'NFL Defensive Player of the Year',
    value: 'nfl_defensive_player_of_the_year',
  },
]

export const listPreviousTeams = [
  { name: 'Los Angeles Lakers', value: 'los_angeles_lakers' },
  { name: 'Golden State Warriors', value: 'golden_state_warriors' },
  { name: 'Chicago Bulls', value: 'chicago_bulls' },
  { name: 'Boston Celtics', value: 'boston_celtics' },
  { name: 'Miami Heat', value: 'miami_heat' },
  { name: 'San Antonio Spurs', value: 'san_antonio_spurs' },
  { name: 'Toronto Raptors', value: 'toronto_raptors' },
  { name: 'Philadelphia 76ers', value: 'philadelphia_76ers' },
  { name: 'Houston Rockets', value: 'houston_rockets' },
  { name: 'Milwaukee Bucks', value: 'milwaukee_bucks' },
  { name: 'Dallas Mavericks', value: 'dallas_mavericks' },
  { name: 'Denver Nuggets', value: 'denver_nuggets' },
  { name: 'Portland Trail Blazers', value: 'portland_trail_blazers' },
  { name: 'New York Knicks', value: 'new_york_knicks' },
  { name: 'Indiana Pacers', value: 'indiana_pacers' },
  { name: 'Utah Jazz', value: 'utah_jazz' },
  { name: 'Brooklyn Nets', value: 'brooklyn_nets' },
  { name: 'Phoenix Suns', value: 'phoenix_suns' },
  { name: 'Oklahoma City Thunder', value: 'oklahoma_city_thunder' },
  { name: 'Atlanta Hawks', value: 'atlanta_hawks' },
  { name: 'Detroit Pistons', value: 'detroit_pistons' },
  { name: 'Minnesota Timberwolves', value: 'minnesota_timberwolves' },
  { name: 'New Orleans Pelicans', value: 'new_orleans_pelicans' },
  { name: 'Cleveland Cavaliers', value: 'cleveland_cavaliers' },
  { name: 'Orlando Magic', value: 'orlando_magic' },
  { name: 'Sacramento Kings', value: 'sacramento_kings' },
  { name: 'Washington Wizards', value: 'washington_wizards' },
  { name: 'Charlotte Hornets', value: 'charlotte_hornets' },
  { name: 'Memphis Grizzlies', value: 'memphis_grizzlies' },
  { name: 'Los Angeles Clippers', value: 'los_angeles_clippers' },
  { name: 'Seattle SuperSonics', value: 'seattle_supersonics' },
  { name: 'Vancouver Grizzlies', value: 'vancouver_grizzlies' },
  { name: 'New Jersey Nets', value: 'new_jersey_nets' },
  { name: 'Charlotte Bobcats', value: 'charlotte_bobcats' },
  { name: 'San Diego Clippers', value: 'san_diego_clippers' },
  { name: 'Kansas City Kings', value: 'kansas_city_kings' },
  { name: 'Buffalo Braves', value: 'buffalo_braves' },
  { name: 'St. Louis Hawks', value: 'st_louis_hawks' },
  { name: 'Syracuse Nationals', value: 'syracuse_nationals' },
  { name: 'Fort Wayne Pistons', value: 'fort_wayne_pistons' },
  { name: 'Rochester Royals', value: 'rochester_royals' },
  { name: 'Indianapolis Jets', value: 'indianapolis_jets' },
  { name: 'Cincinnati Royals', value: 'cincinnati_royals' },
  { name: 'Chicago Stags', value: 'chicago_stags' },
  { name: 'Washington Capitols', value: 'washington_capitols' },
  { name: 'Providence Steamrollers', value: 'providence_steamrollers' },
  { name: 'Toronto Huskies', value: 'toronto_huskies' },
  { name: 'Pittsburgh Ironmen', value: 'pittsburgh_ironmen' },
  { name: 'Indianapolis Olympians', value: 'indianapolis_olympians' },
  { name: 'Waterloo Hawks', value: 'waterloo_hawks' },
  { name: 'St. Louis Bombers', value: 'st_louis_bombers' },
  { name: 'Chicago American Gears', value: 'chicago_american_gears' },
  { name: 'Denver Nuggets (1948)', value: 'denver_nuggets_1948' },
  { name: 'Sheboygan Red Skins', value: 'sheboygan_red_skins' },
  { name: 'Anderson Packers', value: 'anderson_packers' },
  { name: 'Tri-Cities Blackhawks', value: 'tri_cities_blackhawks' },
  { name: 'Baltimore Bullets', value: 'baltimore_bullets' },
  { name: 'Chicago Packers', value: 'chicago_packers' },
  { name: 'Milwaukee Hawks', value: 'milwaukee_hawks' },
  { name: 'Kansas City-Omaha Kings', value: 'kansas_city_omaha_kings' },
  { name: 'New Orleans / Utah Jazz', value: 'new_orleans_utah_jazz' },
  { name: 'San Diego / Houston Rockets', value: 'san_diego_houston_rockets' },
]

export const listDiscipline = [
  { name: 'Alpine Skiing', value: 'alpine_skiing' },
  { name: 'Artistic Gymnastics', value: 'artistic_gymnastics' },
  { name: 'Beach Volleyball', value: 'beach_volleyball' },
  { name: 'BMX Freestyle', value: 'bmx_freestyle' },
  { name: 'Cross-Country Skiing', value: 'cross_country_skiing' },
  { name: 'Cyclocross', value: 'cyclocross' },
  { name: 'Diving', value: 'diving' },
  { name: 'Figure Skating', value: 'figure_skating' },
  { name: 'Gymnastics (Rhythmic)', value: 'gymnastics_rhythmic' },
  { name: 'Ice Hockey', value: 'ice_hockey' },
  {
    name: 'Martial Arts (Judo, Karate, Taekwondo)',
    value: 'martial_arts_judo_karate_taekwondo',
  },
  { name: 'Mountain Biking', value: 'mountain_biking' },
  { name: 'Rhythmic Gymnastics', value: 'rhythmic_gymnastics' },
  { name: 'Ski Jumping', value: 'ski_jumping' },
  {
    name: 'Snowboarding (Halfpipe, Slopestyle)',
    value: 'snowboarding_halfpipe_slopestyle',
  },
  { name: 'Synchronized Swimming', value: 'synchronized_swimming' },
  { name: 'Trampoline Gymnastics', value: 'trampoline_gymnastics' },
  { name: 'Triathlon', value: 'triathlon' },
  { name: 'Volleyball (Indoor)', value: 'volleyball_indoor' },
  { name: 'Water Polo', value: 'water_polo' },
  {
    name: 'Wrestling (Freestyle, Greco-Roman)',
    value: 'wrestling_freestyle_greco_roman',
  },
  { name: 'Archery', value: 'archery' },
  { name: 'Badminton', value: 'badminton' },
  { name: 'Baseball', value: 'baseball' },
  { name: 'Basketball', value: 'basketball' },
  { name: 'Boxing', value: 'boxing' },
  { name: 'Canoeing (Sprint, Slalom)', value: 'canoeing_sprint_slalom' },
  { name: 'Curling', value: 'curling' },
  {
    name: 'Equestrian (Dressage, Eventing, Jumping)',
    value: 'equestrian_dressage_eventing_jumping',
  },
  { name: 'Fencing', value: 'fencing' },
  { name: 'Field Hockey', value: 'field_hockey' },
  { name: 'Football (Soccer)', value: 'football_soccer' },
  { name: 'Golf', value: 'golf' },
  { name: 'Handball', value: 'handball' },
  { name: 'Lacrosse', value: 'lacrosse' },
  { name: 'Modern Pentathlon', value: 'modern_pentathlon' },
  { name: 'Rowing', value: 'rowing' },
  { name: 'Rugby (Sevens, Union)', value: 'rugby_sevens_union' },
  { name: 'Sailing', value: 'sailing' },
  { name: 'Shooting', value: 'shooting' },
  { name: 'Skateboarding', value: 'skateboarding' },
  { name: 'Speed Skating', value: 'speed_skating' },
  { name: 'Surfing', value: 'surfing' },
  { name: 'Swimming', value: 'swimming' },
  { name: 'Table Tennis', value: 'table_tennis' },
  { name: 'Tennis', value: 'tennis' },
  { name: 'Track and Field (Athletics)', value: 'track_and_field_athletics' },
  { name: 'Weightlifting', value: 'weightlifting' },
  {
    name: 'Wrestling (Freestyle, Greco-Roman)',
    value: 'wrestling_freestyle_greco_roman',
  },
]

export const listExperience = [
  { name: 'Alumni', value: 'alumni' },
  { name: 'College', value: 'college' },
  { name: 'Freshmen', value: 'freshmen' },
  { name: 'High School', value: 'high_school' },
  { name: 'Junior', value: 'junior' },
  { name: 'Olympian', value: 'olympian' },
  { name: 'Olympic Hopeful', value: 'olympic_hopeful' },
  { name: 'Paralympian', value: 'paralympian' },
  { name: 'Paralympic Hopeful', value: 'paralympic_hopeful' },
  { name: 'Senior', value: 'senior' },
  { name: 'Sophomore', value: 'sophomore' },
]

export const listLeagueConferences = [
  { name: 'NSL', value: 'nsl' },
  { name: 'GSL', value: 'gsl' },
  { name: 'IBA', value: 'iba' },
  { name: 'WRC', value: 'wrc' },
  { name: 'PTA', value: 'pta' },
  { name: 'GCL', value: 'gcl' },
  { name: 'MBF', value: 'mbf' },
  { name: 'NHA', value: 'nha' },
  { name: 'PGT', value: 'pgt' },
  { name: 'WSL', value: 'wsl' },
  { name: 'IVA', value: 'iva' },
  { name: 'GEC', value: 'gec' },
  { name: 'NMAL', value: 'nmal' },
  { name: 'PARS', value: 'pars' },
  { name: 'WCF', value: 'wcf' },
  { name: 'GTTL', value: 'gttl' },
  { name: 'NLA', value: 'nla' },
  { name: 'PTFL', value: 'ptfl' },
  { name: 'WGC', value: 'wgc' },
  { name: 'ISS', value: 'iss' },
  { name: 'GAL', value: 'gal' },
  { name: 'NESL', value: 'nesl' },
  { name: 'PST', value: 'pst' },
  { name: 'WBSA', value: 'wbsa' },
  { name: 'IBC', value: 'ibc' },
  { name: 'GJF', value: 'gjf' },
  { name: 'NKL', value: 'nkl' },
  { name: 'PFA', value: 'pfa' },
  { name: 'WTA', value: 'wta' },
  { name: 'GPL', value: 'gpl' },
  { name: 'NSSS', value: 'nsss' },
  { name: 'PRC', value: 'prc' },
  { name: 'WISA', value: 'wisa' },
  { name: 'IWF', value: 'iwf' },
  { name: 'GWPL', value: 'gwpl' },
  { name: 'NDA', value: 'nda' },
  { name: 'PBT', value: 'pbt' },
  { name: 'WEC', value: 'wec' },
  { name: 'ICKF', value: 'ickf' },
  { name: 'GRDL', value: 'grdl' },
  { name: 'NUFL', value: 'nufl' },
  { name: 'PCS', value: 'pcs' },
  { name: 'WTA', value: 'wta' },
  { name: 'ISC', value: 'isc' },
  { name: 'GHML', value: 'ghml' },
  { name: 'NOA', value: 'noa' },
  { name: 'PCF', value: 'pcf' },
  { name: 'WSWA', value: 'wswa' },
  { name: 'International Tech Summit', value: 'international_tech_summit' },
  { name: 'Global Marketing Symposium', value: 'global_marketing_symposium' },
  { name: 'World Education Expo', value: 'world_education_expo' },
  {
    name: 'Medical Innovation Conference',
    value: 'medical_innovation_conference',
  },
  {
    name: 'Environmental Sustainability Forum',
    value: 'environmental_sustainability_forum',
  },
  {
    name: 'Digital Transformation Congress',
    value: 'digital_transformation_congress',
  },
  {
    name: 'Artificial Intelligence Symposium',
    value: 'artificial_intelligence_symposium',
  },
  { name: 'Business Leadership Summit', value: 'business_leadership_summit' },
  {
    name: 'Future of Healthcare Conference',
    value: 'future_of_healthcare_conference',
  },
  { name: 'Renewable Energy Expo', value: 'renewable_energy_expo' },
  { name: 'Space Exploration Congress', value: 'space_exploration_congress' },
  { name: 'Innovation in Finance Forum', value: 'innovation_in_finance_forum' },
  { name: 'Human Rights Symposium', value: 'human_rights_symposium' },
  { name: 'Economic Development Summit', value: 'economic_development_summit' },
  { name: 'Green Technology Conference', value: 'green_technology_conference' },
  { name: 'Fashion and Design Expo', value: 'fashion_and_design_expo' },
  { name: 'Cybersecurity Conference', value: 'cybersecurity_conference' },
  { name: 'Food and Beverage Symposium', value: 'food_and_beverage_symposium' },
  {
    name: 'Sustainable Agriculture Forum',
    value: 'sustainable_agriculture_forum',
  },
  { name: 'International Film Festival', value: 'international_film_festival' },
  { name: 'Travel and Tourism Summit', value: 'travel_and_tourism_summit' },
  { name: 'Global Music Conference', value: 'global_music_conference' },
  { name: 'Health and Wellness Expo', value: 'health_and_wellness_expo' },
  { name: 'Renewable Energy Congress', value: 'renewable_energy_congress' },
  { name: 'Education Technology Forum', value: 'education_technology_forum' },
  {
    name: 'International Literature Conference',
    value: 'international_literature_conference',
  },
  { name: 'Entrepreneurship Expo', value: 'entrepreneurship_expo' },
  { name: 'Global Sports Summit', value: 'global_sports_summit' },
  { name: 'Tech Startups Conference', value: 'tech_startups_conference' },
  {
    name: 'Science and Research Symposium',
    value: 'science_and_research_symposium',
  },
  {
    name: 'Blockchain and Cryptocurrency Expo',
    value: 'blockchain_and_cryptocurrency_expo',
  },
  { name: 'Art and Culture Festival', value: 'art_and_culture_festival' },
  {
    name: 'Aerospace and Aviation Conference',
    value: 'aerospace_and_aviation_conference',
  },
  { name: 'Global Climate Change Forum', value: 'global_climate_change_forum' },
  {
    name: 'Leadership Development Seminar',
    value: 'leadership_development_seminar',
  },
  { name: 'International Trade Expo', value: 'international_trade_expo' },
  {
    name: 'Psychology and Mental Health Conference',
    value: 'psychology_and_mental_health_conference',
  },
  {
    name: 'Robotics and Automation Summit',
    value: 'robotics_and_automation_summit',
  },
  {
    name: 'Future of Transportation Symposium',
    value: 'future_of_transportation_symposium',
  },
  {
    name: 'Fashion Technology Conference',
    value: 'fashion_technology_conference',
  },
  { name: 'Space Technology Expo', value: 'space_technology_expo' },
  {
    name: 'Global Food and Agriculture Forum',
    value: 'global_food_and_agriculture_forum',
  },
  {
    name: 'International Renewable Resources Congress',
    value: 'international_renewable_resources_congress',
  },
  {
    name: 'Blockchain and Decentralized Finance Summit',
    value: 'blockchain_and_decentralized_finance_summit',
  },
  {
    name: 'Bioinformatics and Genomics Symposium',
    value: 'bioinformatics_and_genomics_symposium',
  },
  {
    name: 'Green Energy Technology Conference',
    value: 'green_energy_technology_conference',
  },
]

export const listTeams = [
  { name: 'Los Angeles Lakers', value: 'los_angeles_lakers' },
  { name: 'Golden State Warriors', value: 'golden_state_warriors' },
  { name: 'Chicago Bulls', value: 'chicago_bulls' },
  { name: 'Boston Celtics', value: 'boston_celtics' },
  { name: 'Miami Heat', value: 'miami_heat' },
  { name: 'San Antonio Spurs', value: 'san_antonio_spurs' },
  { name: 'Toronto Raptors', value: 'toronto_raptors' },
  { name: 'Philadelphia 76ers', value: 'philadelphia_76ers' },
  { name: 'Houston Rockets', value: 'houston_rockets' },
  { name: 'Milwaukee Bucks', value: 'milwaukee_bucks' },
  { name: 'Dallas Mavericks', value: 'dallas_mavericks' },
  { name: 'Denver Nuggets', value: 'denver_nuggets' },
  { name: 'Portland Trail Blazers', value: 'portland_trail_blazers' },
  { name: 'New York Knicks', value: 'new_york_knicks' },
  { name: 'Indiana Pacers', value: 'indiana_pacers' },
  { name: 'Utah Jazz', value: 'utah_jazz' },
  { name: 'Brooklyn Nets', value: 'brooklyn_nets' },
  { name: 'Phoenix Suns', value: 'phoenix_suns' },
  { name: 'Oklahoma City Thunder', value: 'oklahoma_city_thunder' },
  { name: 'Atlanta Hawks', value: 'atlanta_hawks' },
  { name: 'Detroit Pistons', value: 'detroit_pistons' },
  { name: 'Minnesota Timberwolves', value: 'minnesota_timberwolves' },
  { name: 'New Orleans Pelicans', value: 'new_orleans_pelicans' },
  { name: 'Cleveland Cavaliers', value: 'cleveland_cavaliers' },
  { name: 'Orlando Magic', value: 'orlando_magic' },
  { name: 'Sacramento Kings', value: 'sacramento_kings' },
  { name: 'Washington Wizards', value: 'washington_wizards' },
  { name: 'Charlotte Hornets', value: 'charlotte_hornets' },
  { name: 'Memphis Grizzlies', value: 'memphis_grizzlies' },
  { name: 'Los Angeles Clippers', value: 'los_angeles_clippers' },
  { name: 'Seattle SuperSonics', value: 'seattle_supersonics' },
  { name: 'Vancouver Grizzlies', value: 'vancouver_grizzlies' },
  { name: 'New Jersey Nets', value: 'new_jersey_nets' },
  { name: 'Charlotte Bobcats', value: 'charlotte_bobcats' },
  { name: 'San Diego Clippers', value: 'san_diego_clippers' },
  { name: 'Kansas City Kings', value: 'kansas_city_kings' },
  { name: 'Buffalo Braves', value: 'buffalo_braves' },
  { name: 'St. Louis Hawks', value: 'st_louis_hawks' },
  { name: 'Syracuse Nationals', value: 'syracuse_nationals' },
  { name: 'Fort Wayne Pistons', value: 'fort_wayne_pistons' },
  { name: 'Rochester Royals', value: 'rochester_royals' },
  { name: 'Indianapolis Jets', value: 'indianapolis_jets' },
  { name: 'Cincinnati Royals', value: 'cincinnati_royals' },
  { name: 'Chicago Stags', value: 'chicago_stags' },
  { name: 'Washington Capitols', value: 'washington_capitols' },
  { name: 'Providence Steamrollers', value: 'providence_steamrollers' },
  { name: 'Toronto Huskies', value: 'toronto_huskies' },
  { name: 'Pittsburgh Ironmen', value: 'pittsburgh_ironmen' },
  { name: 'Indianapolis Olympians', value: 'indianapolis_olympians' },
  { name: 'Waterloo Hawks', value: 'waterloo_hawks' },
  { name: 'St. Louis Bombers', value: 'st_louis_bombers' },
  { name: 'Chicago American Gears', value: 'chicago_american_gears' },
  { name: 'Denver Nuggets (1948)', value: 'denver_nuggets_1948' },
  { name: 'Sheboygan Red Skins', value: 'sheboygan_red_skins' },
  { name: 'Anderson Packers', value: 'anderson_packers' },
  { name: 'Tri-Cities Blackhawks', value: 'tri_cities_blackhawks' },
  { name: 'Baltimore Bullets', value: 'baltimore_bullets' },
  { name: 'Chicago Packers', value: 'chicago_packers' },
  { name: 'Milwaukee Hawks', value: 'milwaukee_hawks' },
  { name: 'Kansas City-Omaha Kings', value: 'kansas_city_omaha_kings' },
  { name: 'New Orleans / Utah Jazz', value: 'new_orleans_utah_jazz' },
  { name: 'San Diego / Houston Rockets', value: 'san_diego_houston_rockets' },
]

export const listPosition = [
  { name: 'All Around', value: 'all_around' },
  { name: 'Point Guard', value: 'point_guard' },
  { name: 'Shooting Guard', value: 'shooting_guard' },
  { name: 'Small Forward', value: 'small_forward' },
  { name: 'Power Forward', value: 'power_forward' },
  { name: 'Center', value: 'center' },
]

export const listEthnicity = [
  { name: 'African American', value: 'african_american' },
  { name: 'Alaska Native', value: 'alaska_native' },
  { name: 'American Indian', value: 'american_indian' },
  { name: 'Asian', value: 'asian' },
  { name: 'Black', value: 'black' },
  { name: 'Hispanic', value: 'hispanic' },
  { name: 'Latino', value: 'latino' },
  { name: 'Native Hawaiian', value: 'native_hawaiian' },
  { name: 'Pacific Islander', value: 'pacific_islander' },
  { name: 'White', value: 'white' },
]

export const listLanguages = [
  { name: 'Afrikaans', value: 'afrikaans' },
  { name: 'Amharic', value: 'amharic' },
  { name: 'Arabic', value: 'arabic' },
  { name: 'Bengali', value: 'bengali' },
  { name: 'Bulgarian', value: 'bulgarian' },
  { name: 'Catalan', value: 'catalan' },
  { name: 'Chinese', value: 'chinese' },
  { name: 'Croatian', value: 'croatian' },
  { name: 'Czech', value: 'czech' },
  { name: 'Danish', value: 'danish' },
  { name: 'Dutch', value: 'dutch' },
  { name: 'English', value: 'english' },
  { name: 'Finnish', value: 'finnish' },
  { name: 'French', value: 'french' },
  { name: 'Galician', value: 'galician' },
  { name: 'German', value: 'german' },
  { name: 'Greek', value: 'greek' },
  { name: 'Hausa', value: 'hausa' },
  { name: 'Hindi', value: 'hindi' },
  { name: 'Hungarian', value: 'hungarian' },
  { name: 'Igbo', value: 'igbo' },
  { name: 'Indonesian', value: 'indonesian' },
  { name: 'Italian', value: 'italian' },
  { name: 'Japanese', value: 'japanese' },
  { name: 'Korean', value: 'korean' },
  { name: 'Malay', value: 'malay' },
  { name: 'Norwegian', value: 'norwegian' },
  { name: 'Polish', value: 'polish' },
  { name: 'Portuguese', value: 'portuguese' },
  { name: 'Punjabi', value: 'punjabi' },
  { name: 'Romanian', value: 'romanian' },
  { name: 'Russian', value: 'russian' },
  { name: 'Serbian', value: 'serbian' },
  { name: 'Slovak', value: 'slovak' },
  { name: 'Slovenian', value: 'slovenian' },
  { name: 'Spanish', value: 'spanish' },
  { name: 'Swahili', value: 'swahili' },
  { name: 'Swedish', value: 'swedish' },
  { name: 'Thai', value: 'thai' },
  { name: 'Turkish', value: 'turkish' },
  { name: 'Urdu', value: 'urdu' },
  { name: 'Vietnamese', value: 'vietnamese' },
  { name: 'Yoruba', value: 'yoruba' },
  { name: 'Zulu', value: 'zulu' },
]

export const listInterests = [
  { name: 'Arts & Culture', value: 'arts_and_culture' },
  { name: 'Careers', value: 'careers' },
  { name: 'Business & Finance', value: 'business_and_finance' },
  { name: 'Disability Advocacy', value: 'disability_advocacy' },
  { name: 'Entertainment', value: 'entertainment' },
  { name: 'Fashion & Beauty', value: 'fashion_and_beauty' },
  { name: 'Fitness', value: 'fitness' },
  { name: 'Food', value: 'food' },
  { name: 'Gaming', value: 'gaming' },
  { name: 'Home & Family', value: 'home_and_family' },
  { name: 'Married', value: 'married' },
  { name: 'Military', value: 'military' },
  { name: 'Movies & TV', value: 'movies_and_tv' },
  { name: 'Music', value: 'music' },
  { name: 'News', value: 'news' },
  { name: 'NFTs', value: 'nfts' },
]

export const listWhichBestDescribesYou = [
  { name: 'Professional Athlete', value: 'professional_athlete' },
  { name: 'Student-Athlete', value: 'student_athlete' },
  { name: 'Retired Athlete', value: 'retired_athlete' },
  { name: 'Coach', value: 'coach' },
  { name: 'Staff', value: 'staff' },
  { name: 'Trainer', value: 'trainer' },
  { name: 'Broadcaster', value: 'Broadcaster' },
  { name: 'Sports Exec', value: 'sports_exec' },
]
export const listGenderIdentities = [
  { name: 'Female', value: 'female' },
  { name: 'Male', value: 'male' },
  { name: 'Non-Binary', value: 'non-binary' },
  { name: 'Other Gender', value: 'other Gender' },
]

export const listSports = [
  { name: 'Archery', value: 'archery' },
  { name: 'Badminton', value: 'badminton' },
  { name: 'Baseball', value: 'baseball' },
  { name: 'Basketball', value: 'basketball' },
  { name: 'Climbing', value: 'climbing' },
  { name: 'Fencing', value: 'fencing' },
  { name: 'Golf', value: 'golf' },
  { name: 'Hockey', value: 'hockey' },
  { name: 'Soccer', value: 'soccer' },
  { name: 'Volleyball', value: 'volleyball' },
]

export const listCurrentTeam = [
  { name: 'AC Milan (Serie A)', value: 'ac_milan_serie_a' },
  { name: 'Arizona Cardinals (NFL)', value: 'arizona_cardinals_nfl' },
  { name: 'Arsenal FC (Premier League)', value: 'arsenal_fc_premier_league' },
  { name: 'AS Roma (Serie A)', value: 'as_roma_serie_a' },
  { name: 'Baltimore Ravens (NFL)', value: 'baltimore_ravens_nfl' },
  { name: 'Bayern Munich (Bundesliga)', value: 'bayern_munich_bundesliga' },
  { name: 'Boston Red Sox (MLB)', value: 'boston_red_sox_mlb' },
  { name: 'Chicago Bulls (NBA)', value: 'chicago_bulls_nba' },
  { name: 'Chicago Cubs (MLB)', value: 'chicago_cubs_mlb' },
  { name: 'Chelsea FC (Premier League)', value: 'chelsea_fc_premier_league' },
  { name: 'Cleveland Cavaliers (NBA)', value: 'cleveland_cavaliers_nba' },
  { name: 'Dallas Cowboys (NFL)', value: 'dallas_cowboys_nfl' },
  { name: 'Denver Broncos (NFL)', value: 'denver_broncos_nfl' },
  { name: 'FC Barcelona (La Liga)', value: 'fc_barcelona_la_liga' },
  { name: 'Golden State Warriors (NBA)', value: 'golden_state_warriors_nba' },
  { name: 'Green Bay Packers (NFL)', value: 'green_bay_packers_nfl' },
  { name: 'Houston Rockets (NBA)', value: 'houston_rockets_nba' },
  { name: 'Inter Milan (Serie A)', value: 'inter_milan_serie_a' },
  { name: 'Kansas City Chiefs (NFL)', value: 'kansas_city_chiefs_nfl' },
  {
    name: 'Liverpool FC (Premier League)',
    value: 'liverpool_fc_premier_league',
  },
  { name: 'Los Angeles Dodgers (MLB)', value: 'los_angeles_dodgers_mlb' },
  { name: 'Los Angeles Lakers (NBA)', value: 'los_angeles_lakers_nba' },
  { name: 'Los Angeles Rams (NFL)', value: 'los_angeles_rams_nfl' },
  {
    name: 'Manchester City FC (Premier League)',
    value: 'manchester_city_fc_premier_league',
  },
  {
    name: 'Manchester United FC (Premier League)',
    value: 'manchester_united_fc_premier_league',
  },
  { name: 'Miami Dolphins (NFL)', value: 'miami_dolphins_nfl' },
  { name: 'Miami Heat (NBA)', value: 'miami_heat_nba' },
  { name: 'Minnesota Vikings (NFL)', value: 'minnesota_vikings_nfl' },
  { name: 'New England Patriots (NFL)', value: 'new_england_patriots_nfl' },
  { name: 'New Orleans Saints (NFL)', value: 'new_orleans_saints_nfl' },
  { name: 'New York Giants (NFL)', value: 'new_york_giants_nfl' },
  { name: 'New York Knicks (NBA)', value: 'new_york_knicks_nba' },
  { name: 'New York Lakers (NBA)', value: 'new_york_lakers_nba' },
  { name: 'New York Mets (MLB)', value: 'new_york_mets_mlb' },
  { name: 'New York Yankees (MLB)', value: 'new_york_yankees_mlb' },
  { name: 'Philadelphia Eagles (NFL)', value: 'philadelphia_eagles_nfl' },
  { name: 'Pittsburgh Steelers (NFL)', value: 'pittsburgh_steelers_nfl' },
  { name: 'Portland Trail Blazers (NBA)', value: 'portland_trail_blazers_nba' },
  {
    name: 'Real Madrid Baloncesto (Liga ACB)',
    value: 'real_madrid_baloncesto_liga_acb',
  },
  { name: 'Real Madrid CF (La Liga)', value: 'real_madrid_cf_la_liga' },
  { name: 'San Antonio Spurs (NBA)', value: 'san_antonio_spurs_nba' },
  { name: 'San Francisco 49ers (NFL)', value: 'san_francisco_49ers_nfl' },
  { name: 'Seattle Seahawks (NFL)', value: 'seattle_seahawks_nfl' },
  { name: 'Seattle Sounders FC (MLS)', value: 'seattle_sounders_fc_mls' },
  {
    name: 'Tottenham Hotspur FC (Premier League)',
    value: 'tottenham_hotspur_fc_premier_league',
  },
  { name: 'Toronto Blue Jays (MLB)', value: 'toronto_blue_jays_mlb' },
  { name: 'Toronto Raptors (NBA)', value: 'toronto_raptors_nba' },
  { name: 'Utah Jazz (NBA)', value: 'utah_jazz_nba' },
]

export const listBrandCategories = [
  { name: 'Accounting & Finance', value: 'accounting_finance' },
  { name: 'Advertising & Marketing', value: 'advertising_marketing' },
  { name: 'Agriculture', value: 'agriculture' },
  { name: 'Airlines & Aviation', value: 'airlines_aviation' },
  { name: 'Animal Care', value: 'animal_care' },
  { name: 'Apparel & Fashion', value: 'apparel_fashion' },
  { name: 'Appliances', value: 'appliances' },
  { name: 'Architecture & Engineering', value: 'architecture_engineering' },
  { name: 'Arts & Crafts', value: 'arts_crafts' },
  { name: 'Automotive', value: 'automotive' },
  { name: 'Banking & Financial Services', value: 'banking_financial_services' },
  { name: 'Bars & Restaurants', value: 'bars_restaurants' },
  { name: 'Beauty & Cosmetics', value: 'beauty_cosmetics' },
  { name: 'Biotechnology', value: 'biotechnology' },
  { name: 'Books & Magazines', value: 'books_magazines' },
  { name: 'Business Services', value: 'business_services' },
  { name: 'Chemicals', value: 'chemicals' },
  { name: 'Childcare', value: 'childcare' },
  { name: 'Cleaning & Janitorial', value: 'cleaning_janitorial' },
  { name: 'Clothing & Accessories', value: 'clothing_accessories' },
  { name: 'Computer & Network Security', value: 'computer_network_security' },
  { name: 'Computers & Software', value: 'computers_software' },
  { name: 'Construction', value: 'construction' },
  { name: 'Consulting', value: 'consulting' },
  { name: 'Consumer Goods', value: 'consumer_goods' },
  { name: 'Customer Service', value: 'customer_service' },
  { name: 'Data Science & Analytics', value: 'data_science_analytics' },
  { name: 'Dentistry', value: 'dentistry' },
  { name: 'Design', value: 'design' },
  { name: 'Education', value: 'education' },
  { name: 'Electronics', value: 'electronics' },
  { name: 'Energy & Utilities', value: 'energy_utilities' },
  { name: 'Entertainment', value: 'entertainment' },
  { name: 'Environmental Services', value: 'environmental_services' },
  { name: 'Event Planning & Services', value: 'event_planning_services' },
  { name: 'Facilities Management', value: 'facilities_management' },
  { name: 'Farming', value: 'farming' },
  { name: 'Financial Services', value: 'financial_services' },
  { name: 'Fitness & Wellness', value: 'fitness_wellness' },
  { name: 'Food & Beverage', value: 'food_beverage' },
  { name: 'Forestry & Logging', value: 'forestry_logging' },
  { name: 'Furniture', value: 'furniture' },
  { name: 'Gaming', value: 'gaming' },
  {
    name: 'Government & Public Administration',
    value: 'government_public_administration',
  },
  { name: 'Graphics Design', value: 'graphics_design' },
  { name: 'Grocery Stores', value: 'grocery_stores' },
  { name: 'Hair Salons & Barbershops', value: 'hair_salons_barbershops' },
  { name: 'Healthcare', value: 'healthcare' },
  { name: 'Hospitality & Tourism', value: 'hospitality_tourism' },
  { name: 'Human Resources', value: 'human_resources' },
  { name: 'Insurance', value: 'insurance' },
  { name: 'Internet & Technology', value: 'internet_technology' },
  { name: 'Jewelry & Watches', value: 'jewelry_watches' },
  { name: 'Law & Legal', value: 'law_legal' },
  { name: 'Logistics & Transportation', value: 'logistics_transportation' },
  { name: 'Manufacturing', value: 'manufacturing' },
  { name: 'Marketing & Advertising', value: 'marketing_advertising' },
  { name: 'Media & Entertainment', value: 'media_entertainment' },
  { name: 'Medical Devices', value: 'medical_devices' },
  { name: 'Mental Health Services', value: 'mental_health_services' },
  { name: 'Metals & Mining', value: 'metals_mining' },
  { name: 'Music & Entertainment', value: 'music_entertainment' },
  { name: 'Non-Profit', value: 'non_profit' },
  { name: 'Nursing', value: 'nursing' },
  { name: 'Office Supplies & Equipment', value: 'office_supplies_equipment' },
  { name: 'Oil & Gas', value: 'oil_gas' },
  { name: 'Packaging & Containers', value: 'packaging_containers' },
  { name: 'Parks & Recreation', value: 'parks_recreation' },
  { name: 'Personal Care', value: 'personal_care' },
  { name: 'Pet Supplies', value: 'pet_supplies' },
  {
    name: 'Pharmaceuticals & Biotechnology',
    value: 'pharmaceuticals_biotechnology',
  },
  { name: 'Photography', value: 'photography' },
  { name: 'Physical Therapy', value: 'physical_therapy' },
  { name: 'Plastics & Rubber', value: 'plastics_rubber' },
  { name: 'Professional Services', value: 'professional_services' },
  { name: 'Public Relations', value: 'public_relations' },
  { name: 'Publishing', value: 'publishing' },
  { name: 'Real Estate', value: 'real_estate' },
  { name: 'Recruitment & Staffing', value: 'recruitment_staffing' },
  { name: 'Restaurants & Bars', value: 'restaurants_bars' },
  { name: 'Retail', value: 'retail' },
  { name: 'Security & Investigations', value: 'security_investigations' },
  { name: 'Shipping & Freight', value: 'shipping_freight' },
  { name: 'Social Media Marketing', value: 'social_media_marketing' },
  { name: 'Sports & Fitness', value: 'sports_fitness' },
  { name: 'Staffing & Recruiting', value: 'staffing_recruiting' },
  { name: 'Telecommunications', value: 'telecommunications' },
  { name: 'Temporary Staffing', value: 'temporary_staffing' },
  { name: 'Travel & Tourism', value: 'travel_tourism' },
  { name: 'Veterinary Services', value: 'veterinary_services' },
  { name: 'Waste Management', value: 'waste_management' },
  { name: 'Wholesale Trade', value: 'wholesale_trade' },
  { name: 'Writing & Editing', value: 'writing_editing' },
]
